WebApplication1/WebApplication1/Controllers/EmployeesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models.ViewModels;

namespace WebApplication1.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly EventsContext _context;
        public EmployeesController(EventsContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(int page = 1)
        {
            int pageSize = 25;
            var employees = _context.Employees.ToList();
            IEnumerable<Employee> employeesPerPages = employees
                .OrderBy(x => x.Id)
                .Skip((page - 1) * pageSize)
                .Take(pageSize).ToList();
            PageInfo pageInfo = new PageInfo { pageNumber = page, pageSize = pageSize, totalItems = _context.Employees.Count() };
            EmployeesViewModel evm = new EmployeesViewModel { PageInfo = pageInfo, Employees = employeesPerPages };
            return View(evm);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Employee employee)
        {
            _context.Employees.Add(employee);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("HttpNotFound");
            }
            Employee employee = _context.Employees.Find(id);
            if (employee != null)
            {
                return View(employee);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(Employee employee)
        {
            _context.Entry(employee).State = EntityState.Modified;
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Remove(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("HttpNotFound");
            }
            Employee employee = _context.Employees.Find(id);
            if (employee != null)
            {
                _context.Employees.Remove(employee);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

WebApplication1/WebApplication1/Controllers/EventsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models.ViewModels;

namespace WebApplication1.Controllers
{
    public class EventsController : Controller
    {
        private readonly EventsContext _context;
        public EventsController(EventsContext context)
        {
            _context = context;
        }
        public ActionResult Index(int page = 1)
        {
            int pageSize = 25;
            var events = _context.Events;
            IEnumerable<Event> eventsPerPages = events
                .OrderBy(x => x.Id)
                .Skip((page - 1) * pageSize)
                .Take(pageSize).ToList();
            PageInfo pageInfo = new PageInfo { pageNumber = page, pageSize = pageSize, totalItems = _context.Events.Count() };
            EventsViewModel evm = new EventsViewModel { PageInfo = pageInfo, Events = eventsPerPages };
            return View(evm);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Event Event)
        {
            _context.Events.Add(Event);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("HttpNotFound");
            }
            Event Event = _context.Events.Find(id);
            if (Event != null)
            {
                return View(Event);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(Event Event)
        {
            _context.Entry(Event).State = EntityState.Modified;
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Remove(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("HttpNotFound");
            }
            Event Event = _context.Events.Find(id);
            if (Event != null)
            {
                _context.Events.Remove(Event);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

WebApplication1/WebApplication1/Controllers/FinancingController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using WebApplication1.Models;
using WebApplication1.Models.ViewModels;

namespace WebApplication1.Controllers
{
    public class FinancingController : Controller
    {
        private readonly EventsContext _context;
        public FinancingController(EventsContext context)
        {
            _context = context;
        }

        public ActionResult Index(int page = 1)
        {
            int pageSize = 25;
            var financings = _context.SourcesOfFinancing;
            IEnumerable<SourceOfFinancing> financingsPerPages = financings
                .OrderBy(x => x.Id)
                .Skip((page - 1) * pageSize)
                .Take(pageSize).ToList();
            PageInfo pageInfo = new PageInfo { pageNumber = page, pageSize = pageSize, totalItems = _context.SourcesOfFinancing.Count() };
            FinancingViewModel fvm = new FinancingViewModel { PageInfo = pageInfo, Financings = financingsPerPages };
            return View(fvm);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(SourceOfFinancing financing)
        {
            _context.SourcesOfFinancing.Add(financing);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("HttpNotFound");
            }
            SourceOfFinancing financing = _context.SourcesOfFinancing.Find(id);
            if (financing != null)
            {
                return View(financing);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(SourceOfFinancing financing)
        {
            _context.Entry(financing).State = EntityState.Modified;
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Remove(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("HttpNotFound");
            }
            SourceOfFinancing financing = _context.SourcesOfFinancing.Find(id);
            if (financing != null)
            {
                _context.SourcesOfFinancing.Remove(financing);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

WebApplication1/WebApplication1/Controllers/PlanningController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using WebApplication1.Models;
using WebApplication1.Models.ViewModels;

namespace WebApplication1.Controllers
{
    public class PlanningController : Controller
    {
        private readonly EventsContext _context;
        public PlanningController(EventsContext context)
        {
            _context = context;
        }
        public ActionResult Index(int page = 1)
        {
            int pageSize = 25;
            var plannedEvents = _context.PlannedEvents.Include(e => e.Enterprise).Include(e => e.Event).Include(e => e.Responsible).Include(e => e.Finance);
            IEnumerable<PlannedEvent> eventsPerPages = plannedEvents
                .OrderBy(x => x.Id)
                .Skip((page - 1) * pageSize)
                .Take(pageSize).ToList();
            PageInfo pageInfo = new PageInfo { pageNumber = page, pageSize = pageSize, totalItems = _context.PlannedEvents.Count() };
            PlanningViewModel pvm = new PlanningViewModel { PageInfo = pageInfo, PlannedEvents = eventsPerPages };
            return View(pvm);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpGet]
        public ActionResult Create()
        {
            SelectList events = new(_context.Events, "Id", "Name");
            SelectList enterprises = new(_context.Enterprises, "Id", "Name");
            SelectList employees = new(_context.Employees, "Id", "Surname");
            SelectList financings = new(_context.SourcesOfFinancing, "Id", "Id");
            ViewBag.Events = events;
            ViewBag.Enterprises = enterprises;
            ViewBag.Employees = employees;
            ViewBag.SourcesOfFinancing = financings;
            return View();
        }

        [HttpPost]
        public ActionResult Create(PlannedEvent plannedEvent)
        {
            _context.PlannedEvents.Add(plannedEvent);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if(id == null)
            {
                return RedirectToAction("HttpNotFound");
            }
            PlannedEvent plannedEvent = _context.PlannedEvents.Find(id);
            if(plannedEvent != null) 
            {
                SelectList events = new(_context.Events, "Id", "Name");
                SelectList enterprises = new(_context.Enterprises, "Id", "Name");
                SelectList employees = new(_context.Employees, "Id", "Surname");
                SelectList financings = new(_context.SourcesOfFinancing, "Id", "Id");
                ViewBag.Events = events;
                ViewBag.Enterprises = enterprises;
                ViewBag.Employees = employees;
                ViewBag.SourcesOfFinancing = financings;
                return View(plannedEvent);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(PlannedEvent plannedEvent)
        {
            _context.Entry(plannedEvent).State = EntityState.Modified;
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Remove(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("HttpNotFound");
            }
            PlannedEvent plannedEvent = _context.PlannedEvents.Find(id);
            if (plannedEvent != null)
            {
                _context.PlannedEvents.Remove(plannedEvent);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

WebApplication1/WebApplication1/Views/Shared/HttpNotFound.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h2 color="red">Страница не найдена</h2>
<p>
    Вы пытаетесь удалить или изменить несуществующий объект.
</p>

WebApplication1/WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Planning" asp-action="Index">Планирование</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Enterprises" asp-action="Index">Предприятия</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Отдел кадров</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="Index">Мероприятия</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Financing" asp-action="Index">Таблица финансирования</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Program" asp-action="Index">Программа энергосбережения</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EventsFinancing" asp-action="Index">Финансирование мероприятий</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Планирование энергосберегающих мероприятий
        </div>
    </footer> -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>